### ISSUE TITLE
Calcolo hash non avviene su elementi dello shingle set ma sui singoli tag

### ISSUE THREAD

**Issue by antonio-turco** [Progetto-Agiw/Vertex-Clustering#1]
https://github.com/Progetto-Agiw/Vertex-Clustering/blob/eba83141262dea97e3c6bdf111514fa09fb49139/core/ShingleVectorFactory.py#L5-L20

In teoria, per risolvere il problema, dovrebbe bastare calcolare la concatenazione di tutti gli elementi della window dello shingle nella funzione lambda. Quindi poi si dovrà togliere il flatten visto che sennò si perde l'informazione sugli shingle.

**Comment by ale-pavel** [comment]
Problema risolto in committ successivo. E' stato anche cambiato l'attributo di ShingleVector inserendo il riferimento alla webpage e non allo shingle (che era errato)

> https://github.com/Progetto-Agiw/Vertex-Clustering/blob/57fafd61b70b7264f1f9e180ff354fa9312cb560/core/ShingleVectorFactory.py#L13-L31
